name: Django CI/CD Pipeline with Coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sosyalmedya_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Reposu Klonla
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Bağımlılıkları Kur
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Django Migration ve Testler + Coverage
        run: |
          source venv/bin/activate
          cd backend
          python manage.py makemigrations
          python manage.py migrate
          coverage run --source='.' manage.py test
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: hzvolkan/myproject
          fail_ci_if_error: true

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      DATABASE_NAME: sosyalmedya_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432